@file:Suppress("FunctionName")

package io.github.reactivecircus.appversioning.tasks

import com.google.common.truth.Truth.assertThat
import io.github.reactivecircus.appversioning.fixtures.AppProjectTemplate
import io.github.reactivecircus.appversioning.fixtures.withFixtureRunner
import io.github.reactivecircus.appversioning.internal.GitClient
import org.gradle.testkit.runner.TaskOutcome
import org.junit.Rule
import org.junit.Test
import org.junit.rules.TemporaryFolder

class PrintAppVersionInfoTest {

    @get:Rule
    val fixtureDir = TemporaryFolder()

    @Test
    fun `PrintAppVersionInfo prints latest generated versionCode and versionName to the console when they are available`() {
        GitClient.initialize(fixtureDir.root).apply {
            val commitId = commit(message = "1st commit.")
            tag(name = "1.2.3", message = "1st tag", commitId = commitId)
        }

        val flavors = listOf("mock", "prod")
        val runner = withFixtureRunner(
            fixtureDir = fixtureDir,
            subprojects = listOf(AppProjectTemplate(flavors = flavors))
        )

        runner.runAndCheckResult(
            "generateAppVersionInfoForProdRelease"
        ) {
            assertThat(task(":app:generateAppVersionInfoForProdRelease")?.outcome).isEqualTo(TaskOutcome.SUCCESS)
        }

        runner.runAndCheckResult(
            "printAppVersionInfoForProdRelease"
        ) {
            assertThat(task(":app:printAppVersionInfoForProdRelease")?.outcome).isEqualTo(TaskOutcome.SUCCESS)
            assertThat(output).contains(
                """
                    App version info generated by Android App Versioning Plugin:
                    Build variant: prodRelease
                    versionCode: 10203
                    versionName: "1.2.3"
                """.trimIndent()
            )
        }
    }

    @Test
    fun `PrintAppVersionInfo prints warning message to the console when they are not available`() {
        GitClient.initialize(fixtureDir.root).apply {
            val commitId = commit(message = "1st commit.")
            tag(name = "1.2.3", message = "1st tag", commitId = commitId)
        }

        withFixtureRunner(
            fixtureDir = fixtureDir,
            subprojects = listOf(AppProjectTemplate())
        ).runAndCheckResult(
            "printAppVersionInfoForRelease"
        ) {
            assertThat(task(":app:printAppVersionInfoForRelease")?.outcome).isEqualTo(TaskOutcome.SUCCESS)
            assertThat(output).contains(
                "No app version info (versionCode and versionName) generated by the Android App Versioning Plugin for the \"release\" variant is available."
            )
        }
    }

    @Test
    fun `PrintAppVersionInfo is not incremental`() {
        GitClient.initialize(fixtureDir.root).apply {
            val commitId = commit(message = "1st commit.")
            tag(name = "0.1.2", message = "1st tag", commitId = commitId)
        }

        val runner = withFixtureRunner(
            fixtureDir = fixtureDir,
            subprojects = listOf(AppProjectTemplate())
        )

        runner.runAndCheckResult(
            "generateAppVersionInfoForRelease"
        ) {
            assertThat(task(":app:generateAppVersionInfoForRelease")?.outcome).isEqualTo(TaskOutcome.SUCCESS)
        }

        runner.runAndCheckResult(
            "printAppVersionInfoForRelease"
        ) {
            assertThat(task(":app:printAppVersionInfoForRelease")?.outcome).isEqualTo(TaskOutcome.SUCCESS)
            assertThat(output).contains(
                """
                    App version info generated by Android App Versioning Plugin:
                    Build variant: release
                    versionCode: 102
                    versionName: "0.1.2"
                """.trimIndent()
            )
        }

        runner.runAndCheckResult(
            "printAppVersionInfoForRelease"
        ) {
            assertThat(task(":app:printAppVersionInfoForRelease")?.outcome).isEqualTo(TaskOutcome.SUCCESS)
            assertThat(output).contains(
                """
                    App version info generated by Android App Versioning Plugin:
                    Build variant: release
                    versionCode: 102
                    versionName: "0.1.2"
                """.trimIndent()
            )
        }
    }
}
