name: CI

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'

env:
  CI: true
  GRADLE_OPTS: -Dkotlin.incremental=false -Dorg.gradle.jvmargs="-Xmx4g -XX:+HeapDumpOnOutOfMemoryError"
  TERM: dumb

jobs:
  assemble:
    name: Assemble
    runs-on: ubuntu-latest
    env:
      JAVA_TOOL_OPTIONS: -Xmx4g -XX:+UseParallelGC

    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '15'
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: assemble

  checks:
    name: Checks (unit tests, static analysis, plugin validations and binary compatibility API check)
    runs-on: ubuntu-latest
    env:
      JAVA_TOOL_OPTIONS: -Xmx4g -XX:+UseParallelGC

    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '15'
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: test detekt validatePlugins apiCheck

  functional-tests:
    name: Functional tests
    runs-on: ubuntu-latest
    env:
      JAVA_TOOL_OPTIONS: -Xmx4g -XX:+UseParallelGC
      AGP_VERSION: ${{ matrix.agp-version }}
    strategy:
      matrix:
        agp-version: [ 7.0.3, 7.1.0-beta03, 7.2.0-alpha04 ]

    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '15'
      - name: Configure git user
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: functionalTest

  deploy-snapshot:
    name: Deploy snapshot
    needs: [assemble, checks, functional-tests]
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    env:
      JAVA_TOOL_OPTIONS: -Xmx4g -XX:+UseParallelGC
      ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.SONATYPE_NEXUS_USERNAME }}
      ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.SONATYPE_NEXUS_PASSWORD }}

    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '15'
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: clean kotlinSourcesJar publish --no-daemon --no-parallel --no-configuration-cache
